import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <nav>
          <ul style={{ display: "flex", gap: "1rem", listStyle: "none", padding: 0 }}>
            <li>
              <Link href="/produtos">Produtos</Link>
            </li>
            <li>
              <Link href="/tecnologias">Tecnologias</Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
